name: x
permissions:
  contents: read
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
env:
  CGO: 0
jobs:
  x-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Fetch base ref for PR
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
      # Run crie through its action
      - name: Run crie all
        uses: tyhal/crie-action@283048b00daf6ce74442d38aa76e77f9472b581b # main
        with:
          command: lnt
          lint_continue: 'true'
          lint_passes: 'true'
          lint_git_diff: ${{ github.event_name == 'pull_request'  && 'true' || 'false' }}
          lint_git_target: ${{ github.event_name == 'pull_request' && format('origin/{0}', github.base_ref || github.ref_name) || '' }}
      - name: Ensure no diff
        run: git diff --exit-code
